### ISSUE TITLE
V-Express Features Not Working in Interface

### ISSUE THREAD

**Issue by M4K4R** [tiankuan93/ComfyUI-V-Express#3]
**Description:**
I have installed the ComfyUI-V-Express repository on my ComfyUI server hosted on Huggingface. However, I am unable to use some features related to V-Express in the interface. Options like "Set V-Express Model Path" are not functioning. I need assistance to resolve this issue. I have attached a screenshot for reference.

**Steps to Reproduce:**
1. Install the ComfyUI-V-Express repository on a ComfyUI server hosted on Huggingface.
2. Navigate to the interface section.
3. Attempt to use options like "Set V-Express Model Path" from the menu.

**Expected Behavior:**
These options should work, allowing paths to be set without issues.

**Actual Behavior:**
These options are non-functional. Settings cannot be applied or saved.

**Additional Information:**

- Screenshot attached.
![Screenshot_1](https://github.com/tiankuan93/ComfyUI-V-Express/assets/37383837/78f57f4f-8ae3-49a8-97a6-0919e37709ce)

- ComfyUI version: 2221[b24986](2024-06-01)

**Can you provide guidance on how to resolve this issue? Thank you for your help.**

**Comment by tiankuan93** [comment]
I'm not sure if this has anything to do with the name of the node. To avoid potential risks, I updated some of the node names to make them more reasonable. You can pull the latest repository and workflow to try it.

**Comment by tiankuan93** [comment]
It looks like you didn't download all the models. You need to download the model according to the [installation](https://github.com/tiankuan93/ComfyUI-V-Express#installation) and put it in the correct path.
