### ISSUE TITLE
How to run mode with only input pictures and audio？

### ISSUE THREAD

**Issue by 2265865006** [tiankuan93/ComfyUI-V-Express#7]
How to run mode with only input pictures and audio？Just like the official warehouse Scenario 2 (A's picture and any talking audio.)

**Comment by tiankuan93** [comment]
1. You should update the newest `ComfyUI-V-Express`.
2. You can pick any kps path as the kps input and set `retarget_strategy` to `fix_face`. Workflow will ignore the kps input.

<img width="423" alt="image" src="https://github.com/tiankuan93/ComfyUI-V-Express/assets/19601425/b024e011-65c9-4e23-a526-861163c19fab">

**Comment by 2265865006** [comment]
thanks,I understand
